"""
Query chunk by recipe name from ChromaDB vector database
Usage: python test-scripts/query_chunk.py "White Tofu"
"""
import sys
import os
import chromadb
from chromadb.config import Settings
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

def query_chunk_by_name(name):
    """
    Query chunk content by recipe name
    
    Args:
        name: Recipe name to search for
    """
    # Get database path from environment
    db_path = os.getenv("CHROMA_DB_PATH", "./vector_db")
    
    # Initialize ChromaDB client
    client = chromadb.PersistentClient(
        path=db_path,
        settings=Settings(anonymized_telemetry=False)
    )
    
    # Get collection
    collection = client.get_collection("knowledge_base")
    
    print("=" * 80)
    print(f"🔍 Querying chunk with name = '{name}'")
    print("=" * 80)
    
    try:
        # Query using metadata filter
        results = collection.get(
            where={"name": name},
            include=["documents", "metadatas", "embeddings"]
        )
        
        # Check if results found
        if not results["documents"]:
            print(f"\n❌ No chunk found with name = '{name}'")
            print(f"\n💡 Tip: Use the following command to see all available recipes:")
            print(f"   python test-scripts/list_recipes.py")
            return
        
        # Display results
        embeddings = results.get("embeddings")
        if embeddings is None or len(embeddings) == 0:
            embeddings = [None] * len(results["documents"])
            
        documents = results["documents"] if results["documents"] else []
        metadatas = results["metadatas"] if results["metadatas"] else []
        
        for idx in range(len(documents)):
            doc = documents[idx]
            meta = metadatas[idx]
            embedding = embeddings[idx] if idx < len(embeddings) else None
            print(f"\n✅ Found chunk #{idx + 1}:")
            print(f"{'='*80}")
            
            # Display chunk as JSON-like structure
            print("\n📦 Chunk Data:")
            print("-" * 80)
            print("{")
            
            # Display document (truncate if too long, escape special characters)
            doc_display = doc.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t')
            # Increase truncate length to show more content, including steps
            if len(doc_display) > 1000:
                doc_display = doc_display[:1000] + "..."
            print(f'  "document": "{doc_display}",')
            
            # Display metadata
            print(f'  "metadata": {{')
            meta_items = list(sorted(meta.items()))
            for i, (key, value) in enumerate(meta_items):
                comma = "," if i < len(meta_items) - 1 else ""
                print(f'    "{key}": "{value}"{comma}')
            print(f'  }},')
            
            # Display embedding information
            if embedding is not None:
                print(f'  "embedding": [')
                first_30 = [round(v, 9) for v in embedding[:30]]
                print(f'    {first_30},')
                print(f'    ... // ({len(embedding)} total values, generated by text-embedding-3-small)')
                print(f'  ]')
            
            print("}")
            print("-" * 80)
            
            print(f"\n{'='*80}\n")
        
        print(f"✅ Total chunks found: {len(results['documents'])}")
        
    except Exception as e:
        print(f"\n❌ Error querying database: {str(e)}")
        raise


def main():
    """Main entry point"""
    if len(sys.argv) < 2:
        print("Usage: python test-scripts/query_chunk.py <recipe_name>")
        print('Example: python test-scripts/query_chunk.py "White Tofu"')
        print('         python test-scripts/query_chunk.py "Apple Jack"')
        sys.exit(1)
    
    # Get recipe name from command line argument
    recipe_name = sys.argv[1]
    
    # Query chunk
    query_chunk_by_name(recipe_name)


if __name__ == "__main__":
    main()
